"""Base compiler: transform vault blocks into tool-specific context strings."""

import logging
from pathlib import Path

from wormhole.config import Config
from wormhole.manifest import build_manifest
from wormhole.scoring import select_blocks
from wormhole.utils import estimate_tokens
from wormhole.vault import Block, list_blocks

logger = logging.getLogger(__name__)

SENTINEL_START = "<!-- WORMHOLE:START -->"
SENTINEL_END = "<!-- WORMHOLE:END -->"

# Section ordering and category mapping
_SECTION_MAP: list[tuple[str, str]] = [
    ("context", "Active Project Context"),
    ("decisions", "Key Decisions"),
    ("corrections", "Recent Corrections"),
    ("failures", "Known Failures (do not re-attempt)"),
    ("architecture", "Architecture"),
    ("discoveries", "Discoveries"),
]

_CONDENSED_WORD_LIMIT = 200


def _condense(text: str, word_limit: int = _CONDENSED_WORD_LIMIT) -> str:
    """Return first ~word_limit words of text, appending ellipsis if truncated."""
    words = text.split()
    if len(words) <= word_limit:
        return text
    return " ".join(words[:word_limit]) + " ..."



class BaseCompiler:
    """Compile vault blocks into a context string for an AI tool."""

    def __init__(self, vault_path: Path, config: Config) -> None:
        self.vault_path = vault_path
        self.config = config

    @property
    def tool_name(self) -> str:
        raise NotImplementedError

    @property
    def budget(self) -> int:
        return self.config.budgets.get(self.tool_name, 2500)

    def compile(self) -> str:
        """Compile vault into context string for the target tool."""
        all_blocks = list_blocks(self.vault_path)
        selected = select_blocks(all_blocks, self.config, self.tool_name)

        # Group selected blocks by category
        by_category: dict[str, list[tuple[Path, Block, float]]] = {}
        for path, block, score in selected:
            by_category.setdefault(block.category, []).append((path, block, score))

        lines: list[str] = ["# Project Memory (auto-generated by Wormhole)", ""]

        max_inlined = self.config.max_inlined

        for category, heading in _SECTION_MAP:
            cat_blocks = by_category.get(category)
            if not cat_blocks:
                continue

            lines.append(f"## {heading}")
            lines.append("")

            if category == "context":
                # Inline full content of context blocks
                for path, block, _score in cat_blocks:
                    lines.append(f"### {block.title}")
                    lines.append("")
                    lines.append(block.content)
                    lines.append("")
            else:
                # Condensed: title + first ~200 words, respect max_inlined
                limit = max_inlined.get(category, 3)
                for path, block, _score in cat_blocks[:limit]:
                    lines.append(f"### {block.title}")
                    lines.append("")
                    lines.append(_condense(block.content))
                    lines.append("")

        # Vault Manifest summary
        manifest_text = build_manifest(self.vault_path, all_blocks)
        lines.append("## Vault Manifest")
        lines.append("")
        lines.append(manifest_text)
        lines.append("")

        return "\n".join(lines)

    def write(self, output_path: Path) -> None:
        """Write compiled context to file, using sentinel markers to preserve existing content."""
        compiled = self.compile()
        sentinel_block = f"{SENTINEL_START}\n{compiled}\n{SENTINEL_END}"

        if output_path.exists():
            existing = output_path.read_text(encoding="utf-8")
            start_idx = existing.find(SENTINEL_START)
            end_idx = existing.find(SENTINEL_END)

            if start_idx != -1 and end_idx != -1:
                # Replace content between markers (inclusive)
                end_idx += len(SENTINEL_END)
                new_content = existing[:start_idx] + sentinel_block + existing[end_idx:]
            else:
                # No markers found -- append
                separator = "\n\n" if existing and not existing.endswith("\n\n") else ""
                if existing and not existing.endswith("\n"):
                    separator = "\n\n"
                new_content = existing + separator + sentinel_block + "\n"
        else:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            new_content = sentinel_block + "\n"

        output_path.write_text(new_content, encoding="utf-8")
        logger.info("Wrote compiled context to %s (%d tokens)", output_path, estimate_tokens(compiled))
